PARTICIPANTS = {
    "VPT001": {
        "profile": {
            "age": "34",
            "sex": "Female",
            "injury": "IT band syndrome, right leg",
            "tester": "KM",
        },
        "trajectory": "improving",
        "weeks": [
            {
                "week": 1,
                "date": "01/08/2024",
                "days_exercised": "5",
                "exercises_per_session": "6",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching"],
                "too_difficult": "No",
                "confident_form": "No",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "2",
                "mileage": "6",
                "running_minutes": "55",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "6",
                "pain_usual": "6",
                "pain_best": "4",
                "pain_worst": "8",
                "notes": "Sharp pain on outside of right knee after mile 2, had to walk",
            },
            {
                "week": 2,
                "date": "01/15/2024",
                "days_exercised": "6",
                "exercises_per_session": "6",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching", "Foot Strength"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Faster cadence", "Squeezing the gluteal muscles"],
                "days_ran": "3",
                "mileage": "8",
                "running_minutes": "72",
                "other_exercise": "Yes",
                "other_exercise_desc": "Cycling 20 min two days for cross training",
                "pain_now": "4",
                "pain_usual": "5",
                "pain_best": "2",
                "pain_worst": "6",
                "notes": "Still some tightness on right IT band but pain is less sharp",
            },
            {
                "week": 3,
                "date": "01/22/2024",
                "days_exercised": "6",
                "exercises_per_session": "8",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Faster cadence", "Squeezing the gluteal muscles", "Soft quiet steps"],
                "days_ran": "4",
                "mileage": "11",
                "running_minutes": "99",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "2",
                "pain_usual": "3",
                "pain_best": "0",
                "pain_worst": "4",
                "notes": "Ran 4 miles Saturday with almost no pain, mild soreness after",
            },
            {
                "week": 4,
                "date": "01/29/2024",
                "days_exercised": "7",
                "exercises_per_session": "8",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching", "Plyometric", "Neuromuscular Control"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Faster cadence", "Slight forward trunk lean"],
                "days_ran": "4",
                "mileage": "14",
                "running_minutes": "125",
                "other_exercise": "Yes",
                "other_exercise_desc": "Yoga once for flexibility",
                "pain_now": "1",
                "pain_usual": "1",
                "pain_best": "0",
                "pain_worst": "3",
                "notes": "No pain during long run, occasional mild ache only after sitting",
            },
        ],
        "final": {
            "days_exercised": "6",
            "exercises_per_session": "8",
            "pain_now": "0",
            "pain_usual": "1",
            "pain_best": "0",
            "pain_worst": "2",
            "mileage": "18",
            "confident_form": "Yes",
            "notes": "Right IT band pain resolved, running pain free, returning to race training",
        },
        "exit": {
            "satisfaction": "Very satisfied",
            "would_recommend": "Yes",
            "comments": "The virtual sessions were easy to follow and the running cues really helped my form",
        },
    },
    "VPT002": {
        "profile": {
            "age": "27",
            "sex": "Male",
            "injury": "Medial tibial stress syndrome (shin splints), both legs",
            "tester": "KM",
        },
        "trajectory": "mixed",
        "weeks": [
            {
                "week": 1,
                "date": "02/29/2024",
                "missed": True,
                "notes": "Missed visit 1, participant did not have time",
            },
            {
                "week": 2,
                "date": "03/07/2024",
                "days_exercised": "3",
                "exercises_per_session": "5",
                "exercise_types": ["Foot Strength", "Stretching"],
                "too_difficult": "Yes",
                "confident_form": "No",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "1",
                "mileage": "2",
                "running_minutes": "20",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "5",
                "pain_usual": "6",
                "pain_best": "3",
                "pain_worst": "7",
                "notes": "Numbness and aching along both shins, stopped run early",
            },
            {
                "week": 3,
                "date": "03/14/2024",
                "days_exercised": "4",
                "exercises_per_session": "5",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength"],
                "too_difficult": "No",
                "confident_form": "No",
                "cues_used": "Yes",
                "cues_list": ["Soft quiet steps"],
                "days_ran": "2",
                "mileage": "3",
                "running_minutes": "30",
                "other_exercise": "Yes",
                "other_exercise_desc": "Elliptical machine 15 minutes to cross train",
                "pain_now": "4",
                "pain_usual": "5",
                "pain_best": "2",
                "pain_worst": "6",
                "notes": "Shin pain a little better, illegible note about new shoes (unclear)",
            },
            {
                "week": 4,
                "date": "03/21/2024",
                "days_exercised": "5",
                "exercises_per_session": "6",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Hip Strength"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Soft quiet steps", "Faster cadence"],
                "days_ran": "3",
                "mileage": "5",
                "running_minutes": "48",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "3",
                "pain_usual": "3",
                "pain_best": "1",
                "pain_worst": "5",
                "notes": "Improving, minimal pain after short easy runs only",
            },
        ],
        "final": {
            "days_exercised": "5",
            "exercises_per_session": "6",
            "pain_now": "1",
            "pain_usual": "2",
            "pain_best": "0",
            "pain_worst": "4",
            "mileage": "9",
            "confident_form": "Yes",
            "notes": "Shin pain much improved, occasional soreness with speed work",
        },
        "exit": {
            "satisfaction": "Satisfied",
            "would_recommend": "Yes",
            "comments": "Missed the first week but the program still helped a lot with my shins",
        },
    },
    "VPT003": {
        "profile": {
            "age": "41",
            "sex": "Female",
            "injury": "Plantar fasciitis, left foot",
            "tester": "RJ",
        },
        "trajectory": "resolved",
        "weeks": [
            {
                "week": 1,
                "date": "05/06/2024",
                "days_exercised": "6",
                "exercises_per_session": "7",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "3",
                "mileage": "9",
                "running_minutes": "80",
                "other_exercise": "Yes",
                "other_exercise_desc": "Swimming 30 minutes twice a week",
                "pain_now": "3",
                "pain_usual": "4",
                "pain_best": "1",
                "pain_worst": "5",
                "notes": "Left heel pain worst with first steps in the morning",
            },
            {
                "week": 2,
                "date": "05/13/2024",
                "days_exercised": "7",
                "exercises_per_session": "8",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Landing feet under hips", "Soft quiet steps"],
                "days_ran": "3",
                "mileage": "10",
                "running_minutes": "88",
                "other_exercise": "Yes",
                "other_exercise_desc": "Swimming twice a week",
                "pain_now": "2",
                "pain_usual": "2",
                "pain_best": "0",
                "pain_worst": "4",
                "notes": "Morning heel pain improving, no pain during runs now",
            },
            {
                "week": 3,
                "date": "05/20/2024",
                "days_exercised": "7",
                "exercises_per_session": "8",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Plyometric", "Neuromuscular Control"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Landing feet under hips"],
                "days_ran": "4",
                "mileage": "13",
                "running_minutes": "110",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "1",
                "pain_usual": "1",
                "pain_best": "0",
                "pain_worst": "2",
                "notes": "Almost no pain, ran 5 miles Sunday with no issues",
            },
            {
                "week": 4,
                "date": "05/27/2024",
                "days_exercised": "7",
                "exercises_per_session": "8",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Landing feet under hips"],
                "days_ran": "4",
                "mileage": "15",
                "running_minutes": "125",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "0",
                "pain_usual": "0",
                "pain_best": "0",
                "pain_worst": "1",
                "notes": "Pain free for the second week in a row, feeling great",
            },
        ],
        "final": {
            "days_exercised": "7",
            "exercises_per_session": "8",
            "pain_now": "0",
            "pain_usual": "0",
            "pain_best": "0",
            "pain_worst": "0",
            "mileage": "20",
            "confident_form": "Yes",
            "notes": "Plantar fasciitis fully resolved, back to full training load pain free",
        },
        "exit": {
            "satisfaction": "Very satisfied",
            "would_recommend": "Yes",
            "comments": "Loved the program, my foot pain is completely gone and I feel stronger",
        },
    },
    "VPT004": {
        "profile": {
            "age": "52",
            "sex": "Male",
            "injury": "Achilles tendinopathy, left leg",
            "tester": "RJ",
        },
        "trajectory": "improving",
        "messiness": 2.3,
        "weeks": [
            {
                "week": 1,
                "date": "06/03/2024",
                "days_exercised": "4",
                "exercises_per_session": "5",
                "exercise_types": ["Foot Strength", "Stretching"],
                "too_difficult": "Yes",
                "confident_form": "No",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "1",
                "mileage": "3",
                "running_minutes": "28",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "6",
                "pain_usual": "6",
                "pain_best": "4",
                "pain_worst": "8",
                "notes": "Left Achilles very stiff and painful first thing in the morning, hurts to go downstairs",
            },
            {
                "week": 2,
                "date": "06/10/2024",
                "days_exercised": "5",
                "exercises_per_session": "6",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength"],
                "too_difficult": "Yes",
                "confident_form": "No",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "2",
                "mileage": "4",
                "running_minutes": "38",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "5",
                "pain_usual": "5",
                "pain_best": "3",
                "pain_worst": "7",
                "notes": "Still stiff, tried the calf raises but heel really hurts by the twentieth one",
            },
            {
                "week": 3,
                "date": "06/17/2024",
                "days_exercised": "6",
                "exercises_per_session": "7",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Neuromuscular Control"],
                "too_difficult": "No",
                "confident_form": "No",
                "cues_used": "Yes",
                "cues_list": ["Soft quiet steps"],
                "days_ran": "3",
                "mileage": "6",
                "running_minutes": "56",
                "other_exercise": "Yes",
                "other_exercise_desc": "Cycling once instead of running to rest the tendon",
                "pain_now": "3",
                "pain_usual": "4",
                "pain_best": "2",
                "pain_worst": "6",
                "notes": "Morning stiffness shorter, tendon still sore after longer runs",
            },
            {
                "week": 4,
                "date": "06/24/2024",
                "days_exercised": "6",
                "exercises_per_session": "8",
                "exercise_types": ["Foot Strength", "Stretching", "Core Strength", "Neuromuscular Control", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Soft quiet steps", "Faster cadence"],
                "days_ran": "4",
                "mileage": "8",
                "running_minutes": "72",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "2",
                "pain_usual": "2",
                "pain_best": "0",
                "pain_worst": "4",
                "notes": "Noticeably better this week, only mild soreness after the longest run",
            },
        ],
        "final": {
            "days_exercised": "6",
            "exercises_per_session": "8",
            "pain_now": "1",
            "pain_usual": "1",
            "pain_best": "0",
            "pain_worst": "3",
            "mileage": "14",
            "confident_form": "Yes",
            "notes": "Achilles pain much improved, back to regular training with careful warmup",
        },
        "exit": {
            "satisfaction": "Satisfied",
            "would_recommend": "Yes",
            "comments": "Slow progress at first but the calf and foot exercises really helped in the end",
        },
    },
    "VPT005": {
        "profile": {
            "age": "31",
            "sex": "Female",
            "injury": "Patellofemoral pain syndrome, right knee",
            "tester": "KM",
        },
        "trajectory": "improving",
        "weeks": [
            {
                "week": 1,
                "date": "07/01/2024",
                "days_exercised": "5",
                "exercises_per_session": "6",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching"],
                "too_difficult": "No",
                "confident_form": "No",
                "cues_used": "No",
                "cues_list": [],
                "days_ran": "2",
                "mileage": "5",
                "running_minutes": "46",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "5",
                "pain_usual": "5",
                "pain_best": "3",
                "pain_worst": "7",
                "notes": "Front of right knee aches going down stairs and after sitting a long time",
            },
            {
                "week": 2,
                "date": "07/08/2024",
                "days_exercised": "6",
                "exercises_per_session": "7",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Squeezing the gluteal muscles"],
                "days_ran": "3",
                "mileage": "7",
                "corrections": {"running_minutes": ("1.5 hours", "90")},
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "4",
                "pain_usual": "4",
                "pain_best": "2",
                "pain_worst": "6",
                "notes": "Wrote the time down wrong at first, meant ninety minutes total not hours",
            },
            {
                "week": 3,
                "date": "07/15/2024",
                "days_exercised": "6",
                "exercises_per_session": "8",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Squeezing the gluteal muscles", "Landing feet under hips"],
                "days_ran": "3",
                "mileage": "8",
                "running_minutes": "70",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "corrections": {"pain_now": ("8", "3")},
                "pain_usual": "3",
                "pain_best": "1",
                "pain_worst": "5",
                "notes": "Wrote down the wrong pain score at first from an old form, fixed it to today's actual pain",
            },
            {
                "week": 4,
                "date": "07/22/2024",
                "days_exercised": "7",
                "exercises_per_session": "8",
                "exercise_types": ["Hip Strength", "Core Strength", "Stretching", "Plyometric"],
                "too_difficult": "No",
                "confident_form": "Yes",
                "cues_used": "Yes",
                "cues_list": ["Squeezing the gluteal muscles"],
                "days_ran": "4",
                "mileage": "10",
                "running_minutes": "85",
                "other_exercise": "No",
                "other_exercise_desc": "",
                "pain_now": "1",
                "pain_usual": "2",
                "pain_best": "0",
                "pain_worst": "3",
                "notes": "Knee feels much steadier now, barely any pain after running",
            },
        ],
        "final": {
            "days_exercised": "6",
            "exercises_per_session": "8",
            "pain_now": "1",
            "pain_usual": "1",
            "pain_best": "0",
            "pain_worst": "2",
            "mileage": "13",
            "confident_form": "Yes",
            "notes": "Right knee pain well controlled, resuming normal running volume",
        },
        "exit": {
            "satisfaction": "Very satisfied",
            "would_recommend": "Yes",
            "comments": "I appreciated how patient the therapist was when I made mistakes filling out the forms",
        },
    },
}
